project:
  type: website
  output-dir: docs   

website:
  title: "Linisha | Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: services.qmd
        text: Services
      - href: contact.qmd
        text: Contact
format:
  html:
    theme: cosmo
    css: styles.css
    
