project:
  type: website

website:
  title: "Linisha | Portfolio"
  navbar:
    left:
      - text: "HOME"
        href: "#home"
      - text: "ABOUT" 
        href: "#about"
      - text: "SERVICES"
        href: "#services"
      - text: "SKILLS"
        href: "#skills"
      - text: "PROJECTS"
        href: "#projects"
      - text: "CONTACT"
        href: "#contact"
    right:
      - text: "Get Started"
        href: "#contact"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: full